### PR TITLE
sync with mkiocccentry/jparse as taged by v1.5.1

### PR DESCRIPTION
**Pull request by lcn2**
Cloned from
[mkiocccentry/jparse](https://github.com/ioccc-src/mkiocccentry/tree/master/jparse) version Release 1.5.1 2024-08-28 as tagged by
[v1.5.1](https://github.com/ioccc-src/mkiocccentry/releases/tag/v1.5.1) (with the exception of `CHANGES.md`) on 2024-Aug-28.

### CODE REVIEW

**Comment by xexyl** [comment]
Thank you very much!

Oddly an action failed. I'll merge and we can figure it out.

Interesting that it required me to approve the actions. I wonder why that is. Maybe there is a setting? Do you recall? Thanks.

**Comment by xexyl** [comment]
Ah. It does not build due to missing `iocccsize.h`. How do you propose this is resolved, Landon?

**Comment by xexyl** [comment]
Let's see what 455a15a3c7ef589332d27a52e332232f9bdcd370 does.

**Comment by xexyl** [comment]
Ah. I forgot. The `dbg` and `dyn_array` facilities are needed too. How do you propose to deal with that? I have them installed on my system which is why it compiled but it doesn't work here.

**Comment by lcn2** [comment]
> Ah. I forgot. The `dbg` and `dyn_array` facilities are needed too. How do you propose to deal with that? I have them installed on my system which is why it compiled but it doesn't work here.

See issue #2 as that might be a better place to discuss.

**Comment by xexyl** [comment]
Annoying typing `#n` links to this. I have to remember to use inline code blocks or not use the `#`. More annoying is that once I deleted the comment to fix it still keeps it. Oh well. I should remember that now .. I thought there was a way to not link to it but maybe not.

**Pull request merged**
